name: Build_Bootstrap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Bootstrap
    runs-on: macos-13

    steps:
#      - name: Setup Xcode version
#        uses: maxim-lobanov/setup-xcode@v1
#        with:
#          xcode-version: 15.1
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

#      - name: Checkout ColorfulX/main
#        uses: actions/checkout@main
#        with:
#          repository: Lakr233/ColorfulX
#          path: ColorfulX

      - name: Build Bootstrap
        run: |
          make package
          mv ./packages/Bootstrap.tipa ./packages/Bootstrap_1.x.tipa

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Bootstrap
          path: ./packages/*.tipa


      - name: Generate Tag & Release Name
        id: generate_name
        run: |
          time=$(date +%Y%m%d%H%M%S)
          release_tag="$time"
          release_name="Bootstrap原版-$(date +%Y%m%d)"
          echo "release_name=$release_name" >> $GITHUB_OUTPUT
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT    

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./packages/*.tipa
          name: ${{ steps.generate_name.outputs.release_name }}
          tag: ${{ steps.generate_name.outputs.release_tag }}
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

